/*
 * This source file was generated by the Gradle 'init' task
 */
package csc.pa7.pa7;

public class Q1 {
    public void rotate(int[][] matrix) {
        int l  = matrix.length;

        int [][]rotated= new int[l][l];
    // Iterate through the original matrix and populate the rotated matrix
    for(int i=0;i<l;i++){
            for(int j=0;j<l;j++){
                rotated[i][j]= matrix[(l-1)-j][i];
        }
    } 
    // Iterate through the original matrix and populate the rotated matrix
    for(int i=0;i<l;i++){
        for(int j=0;j<l;j++){
            matrix [i][j]=rotated[i][j] ;
        }
    } 
    
    
    }
      public void printMatrix(int[][] matrix) {
        for (int[] row : matrix) {
            for (int element : row) {
                System.out.print(element + " ");
            }
            System.out.println();
        }
    }


    public static void main(String[] args) {
        Q1 q1 = new Q1();
        int[][] matrix = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};

        System.out.println("Original Matrix:");
        q1.printMatrix(matrix);

        q1.rotate(matrix);

        System.out.println("\nRotated Matrix:");
        q1.printMatrix(matrix);
    }

  
    


    
}